### ISSUE TITLE
Refactor Update on save Woocommerce/Wordpress plugin with Doomanager

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#54]
Analize and use of API for update on save in Wordpress with Doomanager.

Document code.
Create / update functional tests.
Create Update on save mermaid diagrams in **doomanager repo**.

blocked by https://github.com/doofinder/doofinder-wordpress/issues/44

blocks https://github.com/doofinder/doofinder-wordpress/issues/55 https://github.com/doofinder/doofinder-wordpress/issues/43

**Comment by eduardogomez97** [comment]
The main idea is to use the wordpress webhook to know when an item has been updated. The ID of this item and its type is stored in a database table called doofinder_update_on_save.

You select in the plugin settings how often you want to send the update on save.

After that time the ID's are separated in different lists according to the type. A bulk of data is built for each element of the list and the bulk is sent to an endpoint prepared in doomanager that receives it together with the type. 

In doomanager we pass it through the Items_transformation and send it to DoofAPI to index it in the corresponding index.

**Comment by eduardogomez97** [comment]
I have tried to implement the update on save integration with the wordpress cron. But it presents the same problems as in prestashop, it does not let us use a custom concurrency associating it in php and the associated task does not run because it seems that it would have to be globalized.

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/c93c0699-985f-4b32-8415-05ff9ceb313c)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/631ff002-08d4-48ff-9c51-3b6a85c904cd)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/b3c0348b-6619-4793-9afe-e0c2a14f6fb8)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/8205596a-599c-4d9f-8b3b-8d167a23ff7a)


So we are going to apply the same solution that was applied in Prestashop and I will create a task to investigate the cron with more time.

**Comment by eduardogomez97** [comment]
After starting to develop how to generate the product bulk and the construction of the items I have seen that there was a better alternative that was previously rejected. 

But after researching that alternative and proposing it to @peillis  . We have come to the conclusion that it is the best way to unify the processes. So the new way would be:

- From the plugin in the platform send only the ID's of the products to update. By type and action.
- Doomanager receives that list of ID's and creates a task to launch the indexing.
- Doofeeds obtains the data as it would a complete indexation, but when it takes the list of ID's what it does is create new search criteria in which it calls the REST API specifying the posts that it has to return (according to the ID's).
- The process from here on is the same and the whole transformation is done in the same way.
- Finally the obtained data is indexed.

*** It is necessary to investigate how to do that in this case it does not replace the complete index, it only updates if it exists or creates if it does not. POST -> PATCH**

**Comment by eduardogomez97** [comment]
After researching and discussing it, the best thing to do is to have all plugin clients centered in one library and have both update on save and doofeeds pull from it. So as not to have several bulk build points. For the moment the easiest way is to create your own client in doomanager. We have pending to talk about launching task or do it directly.

**Comment by eduardogomez97** [comment]
All the Wordpress PR has been corrected. But you can not merge until the rest of the tasks are done because you have to upload everything as a single major version.

The part of doomanager has already been uploaded.
