### ISSUE TITLE
Refactor login/signup Woocommerce/Wordpress plugin

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#55]
Analize and use of API for login/signup in Wordpress.

Document code.
Create / update functional tests.
Create / update mermaid diagrams.

blocked by https://github.com/doofinder/doofinder-wordpress/issues/54
blocks https://github.com/doofinder/doofinder-wordpress/issues/43

**Comment by eduardogomez97** [comment]
You have to adapt the woocommerce wizard setup to the wordpress plugin. The wizard would have only three steps.
1.- Select the sector.
2.- We login/signup and with the collected data we save the key and the host. We create the store and the corresponding structure. We save the data created in the wordpress DB as well as the script.

3.- Thank you page and completion.

It has been reduced since the indexing is in charge of doomanager and the internal search was removed from the plugins.

**Comment by eduardogomez97** [comment]
Once the wizard setup form has been adapted, we should finish cleaning up the plugin and adapt it as necessary. As well as the creation of the REST_API keys.

**Comment by eduardogomez97** [comment]
After discussing it with cristobal and leaving the reduction of steps we have come to the conclusion that the indexing status must be able to be consulted from wordpress. So we have to create a section of the plugin in which we can check the information as it is done in prestashop, etc.

**Comment by eduardogomez97** [comment]
The "processing indexation status" has been done in this task: https://github.com/doofinder/doofinder-wordpress/issues/63

At the moment we only need to fix some details of the payload that we have seen to be able to close it. As soon as I have an opening in support or I finish it, I will be able to finish it.

**Comment by eduardogomez97** [comment]
The error has been fixed and is not blocking.
