### ISSUE TITLE
WordPress / WooCommerce Layer V7 support in new plugin

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#84]
Restore V7 layer compatibility in new plugin.

**Comment by eduardogomez97** [comment]
We have been investigating it and it seems that actually to have V7 active with the new plugin when doing the automatic migration nothing is needed. Since the data migration does not modify the script, it only changes the name of the field from woocommerce to wordpress in the database. So if we should be compatible, anyway we have reactivated the field in case the customer wants to modify the script or add options.

We have also seen that currently when doing the get does not take into account the language, it has been corrected.
